services:
  app:
    container_name: bluesky-extended
    build:
      context: .
      dockerfile: prod.Dockerfile
    expose:
      - "3000"
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    env_file:
      - .env

  postgres:
    image: postgres:17-alpine
    expose:
      - "5432"
    env_file:
      - .env
    # environment:
    #   - POSTGRES_PASSWORD=mysecretpassword
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pg_data:
