import localFont from "next/font/local";

import { ThemeProvider } from "@/components/providers/ThemeProvider";

import type { Metadata } from "next";

import "./globals.css";

import { QueryProvider } from "@/components/providers/QueryProvider";

const pretendard = localFont({
  src: "./PretendardJPVariable.woff2",
  display: "swap",
  weight: "45 920",
  variable: "--font-pretendard",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="ko"
      className={`${pretendard.variable}`}
      suppressHydrationWarning
    >
      <body className="bg-linear-to-br from-violet-600 from-10% to-indigo-950 antialiased">
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          <QueryProvider>{children}</QueryProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
